[[redirects]]
  from = "https://testkitchen-davidakennedy.netlify.app/*"
  to = "https://testkitchen.davidakennedy.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.testkitchen.davidakennedy.com/*"
  to = "https://testkitchen.davidakennedy.com/:splat"
  status = 301
  force = true